let industry_names = {

    "Agriculture": "agriculture",
    "Cloud Services": "cloud_services",
    "Aerospace": "aerospace",
    "Architecture / Engineering / Construction": "architecture_engineering_construction",
    "Automotive / Transportation": "automotive",
    "Consumer Internet": "internet",
    "Energy": "energy",
    "Financial Services": "financial_services",
    "Game Development": "game_development",
    "Hardware / Semiconductor": "hardware",
    "Healthcare & Life Sciences": "healthcare_lifesciences",
    "Higher Education / Academia": "higher_education",
    "HPC / Scientific Computing": "supercomputing",
    "Manufacturing": "manufacturing",
    "Media & Entertainment": "media_entertainment",
    "Public Sector": "public_sector",
    "Retail / Consumer Packaged Goods": "retail",
    "Telecommunications": "telecommunications",
    "Other": "",
    '科研 / 高等教育': 'higher_education', // JAPANESE TRANSLATION ja-jp 
    '高等教育 / 研究': 'higher_education',
    '航空 / 航天 / 国防': 'aerospace',
    '农业': 'agriculture',
    '建筑 / 工程  / 房地产 / 設計': 'architecture_engineering_construction',
    '汽车 / 物流 / 交通运输': 'automotive',
    '云服务 / クラウド サービス プロバイダー': 'cloud_services',
    '消费互联网 / IT サービス': 'internet',
    '能源': 'energy',
    '金融服务': 'financial_services',
    '游戏业': 'game_development',
    '硬件 / 半导体': 'hardware',
    '医疗健康和生命科学': 'healthcare_lifesciences',
    '高性能计算 / 超级计算': 'supercomputing',
    '制造业': 'manufacturing',
    '媒体和娱乐 / メディア / エンターテイメント': 'media_entertainment',
    '公共部门 / 公共部門': 'public_sector',
    '餐饮 / 酒店': 'restaurants',
    '零售 / 批发 ': 'retail',
    '智慧城市 / 空间': 'smart_spaces',
    '电信': 'telecommunications',
    '其他': '',
    "その他": '',
    '学術機関  / 高等教育': 'higher_education',
    '航空宇宙': 'aerospace',
    '農業': 'agriculture',
    '建築 / エンジニアリング / 建設': 'architecture_engineering_construction',
    '自動車 / 輸送': 'automotive',
    'クラウド サービス': 'cloud_services',
    '個人向けインターネット': 'internet',
    'エネルギー': 'energy',
    '金融サービス': 'financial_services',
    'ゲーミング': 'game_development',
    'ハードウェア / 半導体': 'hardware',
    'ヘルスケア & ライフ サイエンス': 'healthcare_lifesciences',
    'HPC / スーパーコンピューティング': 'supercomputing',
    '製造': 'manufacturing',
    'メディア & エンターテイメント': 'media_entertainment',
    '公共部門': 'public_sector',
    '飲食店 / クイック サービス': 'restaurants',
    '小売': 'retail',
    'スマート シティ / スマート空間 / テレコミュニケーション': 'telecommunications',
    'テレコミュニケーション': 'telecommunications',
    "物流 & 輸送": "transportation",
    '通信': '',
    "公共部門": "public_sector",   //Translation zh-tw 
    "媒體與娛樂": "media_entertainment",
    "學術研究 / 高等教育": "higher_education",
    "建築/工程/營造": "architecture_engineering_construction",
    "智慧城市 / 太空": "smart_spaces",
    "汽車/運輸": "automotive",
    "消費者網際網路": "internet",
    "硬體 / 半導體": "hardware",
    "能源": "energy",
    "航太": "aerospace",
    "製造": "manufacturing",
    "農業": "agriculture",
    "遊戲": "game_development",
    "醫療照護與生命科學": "healthcare_lifesciences",
    "金融服務": "financial_services",
    "雲端服務": "cloud_services",
    "零售業": "retail",
    "電信業": "telecommunications",
    "餐飲 / 快速服務": "restaurant",
    "高效能運算 / 超級運算": "supercomputing",
    "其他": "",
    "云服务": "cloud_services",    // Translation zh-cn
    "公共部门": "public_sector",
    "农业": "agriculture",
    "制造业": "manufacturing",
    "医疗健康和生命科学": "healthcare_lifesciences",
    "媒体与娱乐": "media_entertainment",
    "学院 / 高等教育": "higher_education",
    "建筑 / 工程 / 建造": "architecture_engineering_construction",
    "智慧城市 / 空间": "smart_spaces",
    "汽车 / 运输": "automotive",
    "活力": "energy",
    "消费互联网": "internet",
    "游戏": "game_development",
    "电信": "telecommunications",
    "硬件 / 半导体": "hardware",
    "航天": "aerospace",
    "金融服务": "financial_services",
    "零售": "retail",
    "餐厅 / 快速服务": "restaurant",
    "高性能计算 / 超级计算": "supercomputing",
    "其他": "",
    "HPC / 슈퍼컴퓨팅": "supercomputing",  // Translation ko-kr
    "게임": "game_development",
    "공공 부문": "public_sector",
    "금융 서비스": "financial_services",
    "농업": "agriculture",
    "레스토랑 / 퀵서비스": "restaurant",
    "리테일": "retail",
    "미디어 및 엔터테인먼트": "media_entertainment",
    "소비자 인터넷": "internet",
    "스마트 시티 / 공간": "smart_spaces",
    "아키텍처 / 엔지니어링/건설": "architecture_engineering_construction",
    "에너지": "energy",
    "자동차 / 운송": "automotive",
    "제조": "manufacturing",
    "클라우드 서비스": "cloud_services",
    "통신": "telecommunications",
    "하드웨어 / 반도체": "hardware",
    "학계 / 고등교육": "higher_education",
    "항공 우주": "aerospace",
    "헬스케어 및 생명과학": "healthcare_lifesciences",
    "기타": "",
    "Aeroespacial": "aerospace",   //Translation pt-br
    "Agricultura": "agriculture",
    "Arquitectura / ingeniería / construcción": "architecture_engineering_construction",
    "Automoción / transporte": "automotive",
    "Cidades Inteligentes / Espaços": "smart_spaces",
    "Energía": "energy",
    "Fabricación": "manufacturing",
    "Games": "game_development",
    "Hardware / semiconductor": "hardware",
    "HPC / supercomputación": "supercomputing",
    "HPC/Informática científica": "supercomputing",
    "Internet de consumo": "internet",
    "Medios audiovisuales y entretenimiento": "media_entertainment",
    "Meio Acadêmico / Ensino Superior": "higher_education",
    "Restaurantes / Fast Food": "restaurant",
    "Salud y biociencias": "healthcare_lifesciences",
    "Sector público": "public_sector",
    "Servicios en la nube": "cloud_services",
    "Servicios financieros": "financial_services",
    "Telecomunicaciones": "telecommunications",
    "Venta al por menor": "retail",
    "Venta al por menor/Bienes de consumo envasados": "retail",
    "Otros": "",
    "Academia / Educación Superior": "higher_education",   // Translation es-la
    "Aeroespacial": "aerospace",
    "Agricultura": "agriculture",
    "Área de la Salud y Ciencias Biológicas": "healthcare_lifesciences",
    "Arquitectura / Ingeniería / Construcción": "architecture_engineering_construction",
    "Automoción / Transporte": "automotive",
    "Ciudades Inteligentes / Espacios": "smart_spaces",
    "Energía": "energy",
    "Gaming": "game_development",
    "Hardware / Semiconductor": "hardware",
    "HPC / Supercomputación": "supercomputing",
    "Internet del Consumidor": "internet",
    "Manufactura": "manufacturing",
    "Medios y Entretenimiento": "media_entertainment",
    "Restaurantes / Fast Food": "restaurant",
    "Sector público": "public_sector",
    "Servicios en el Cloud": "cloud_services",
    "Servicios Financieros": "financial_services",
    "Telecomunicaciones": "telecommunications",
    "Venta Minorista": "retail",
    "Otros": "",
    "Architektur/Maschinenbau/Baugewerbe": "architecture_engineering_construction", // Translation de-de (german)
    "Automobil-/Transportwesen": "automotive",
    "Cloud-Dienste": "cloud_services",
    "Consumer Internet": "internet",
    "Einzelhandel/Konsumgüter": "retail",
    "Energie": "energy",
    "Fertigung": "manufacturing",
    "Finanzdienstleistungen": "financial_services",
    "Gesundheitswesen und Biowissenschaften": "healthcare_lifesciences",
    "Hardware/Halbleiter": "hardware",
    "HPC/Wissenschaftliches Rechnen": "supercomputing",
    "Landwirtschaft": "agriculture",
    "Luft‑ und Raumfahrt": "aerospace",
    "Medien und Unterhaltung": "media_entertainment",
    "Öffentlicher Sektor": "public_sector",
    "Restaurant / Quick-Service": "restaurant",
    "Smart Cities/Spaces": "smart_spaces",
    "Spieleentwicklung": "game_development",
    "Telekommunikation": "telecommunications",
    "Universität/Bildung": "higher_education",
    "Sonstige": "",
    "Aérospatiale": "aerospace", // Translation fr-fr (french)
    "Agriculture": "agriculture",
    "Architecture, ingénierie et construction": "architecture_engineering_construction",
    "Automobile / Transport": "automotive",
    "Enseignement / Université": "higher_education",
    "Gaming": "game_development",
    "HPC / Calcul scientifique": "supercomputing",
    "Industrie énergétique": "energy",
    "Internet grand public": "internet",
    "Médias et divertissement": "media_entertainment",
    "Production": "manufacturing",
    "Produits matériels / Semi-conducteurs": "hardware",
    "Restauration rapide": "restaurant",
    "Santé et sciences de la vie": "healthcare_lifesciences",
    "Secteur public": "public_sector",
    "Services Cloud": "cloud_services",
    "Services financiers": "financial_services",
    "Télécommunications": "telecommunications",
    "Vente au détail / Biens de consommation courante": "retail",
    "Villes et espaces connectés": "smart_spaces",
    "Autre": "",
    "Aeroespacial": "aerospace",  // Translation es-es (spanish)
    "Agricultura": "agriculture",
    "Arquitectura/ingeniería/construcción": "architecture_engineering_construction",
    "Automoción/transporte": "automotive",
    "Ciudades / espacios inteligentes": "smart_spaces",
    "Desarrollo de juegos": "game_development",
    "Educación superior/Ámbito académico": "higher_education",
    "Energía": "energy",
    "Fabricación": "manufacturing",
    "Hardware/semiconductor": "hardware",
    "HPC/Informática científica": "supercomputing",
    "Internet de consumo": "internet",
    "Medios audiovisuales y entretenimiento": "media_entertainment",
    "Restaurante/Servicio rápido": "restaurant",
    "Salud y biociencias": "healthcare_lifesciences",
    "Sector público": "public_sector",
    "Servicios en la nube": "cloud_services",
    "Servicios financieros": "financial_services",
    "Telecomunicaciones": "telecommunications",
    "Venta al por menor/Bienes de consumo envasados": "retail",
    "Otros": "",
    "Aerospaziale": "aerospace", // Translation it-it (italian)
    "Agricoltura": "agriculture",
    "Architettura, ingegneria ed edilizia": "architecture_engineering_construction",
    "Automobili e trasporti": "automotive",
    "Città/Spazi smart": "smart_spaces",
    "Energia": "energy",
    "Hardware/Semiconduttori": "hardware",
    "HPC/Computing scientifico": "supercomputing",
    "Internet per consumatori": "internet",
    "Media e intrattenimento": "media_entertainment",
    "Produzione industriale": "manufacturing",
    "Pubblica amministrazione": "public_sector",
    "Ristorante/Servizio rapido": "restaurant",
    "Sanità e bioscienze": "healthcare_lifesciences",
    "Servizi cloud": "cloud_services",
    "Servizi finanziari": "financial_services",
    "Sviluppo di giochi": "game_development",
    "Telecomunicazioni": "telecommunications",
    "Università/Istruzione": "higher_education",
    "Vendita al dettaglio/Merci imballate per consumatori": "retail",
    "Altro": "",
    "Architektura / inżynieria / budownictwo": "architecture_engineering_construction", // Translation pl-pl (polish)
    "Branża energetyczna i surowcowa": "energy",
    "Branża lotnicza i kosmiczna": "aerospace",
    "Branża produkcyjna": "manufacturing",
    "Inteligentne miasta / przestrzenie": "smart_spaces",
    "Konsumenckie rozwiązania internetowe": "internet",
    "Media i rozrywka": "media_entertainment",
    "Motoryzacja / transport": "automotive",
    "Obliczenia HPC / obliczenia naukowe": "supercomputing",
    "Opieka zdrowotna i nauki przyrodnicze": "healthcare_lifesciences",
    "Restauracja / Restauracja z szybką obsługą": "restaurant",
    "Rolnictwo": "agriculture",
    "Sektor publiczny": "public_sector",
    "Sprzedaż detaliczna / produkty konsumpcyjne": "retail",
    "Sprzęt komputerowy / półprzewodniki": "hardware",
    "Środowisko akademickie / szkolnictwo": "higher_education",
    "Telekomunikacja": "telecommunications",
    "Tworzenie gier": "game_development",
    "Usługi finansowe": "financial_services",
    "Usługi w chmurze": "cloud_services",
    "Inna": "",
    "HPC / научные вычисления": "supercomputing", // Translation ru-ru (russian) 
    "Авиакосмическая промышленность": "aerospace",
    "Автомобили и транспорт": "automotive",
    "Аппаратное обеспечение/полупроводники": "hardware",
    "Архитектура/проектирование/конструирование": "architecture_engineering_construction",
    "Государственный сектор": "public_sector",
    "Здравоохранение и медико-биологические науки": "healthcare_lifesciences",
    "Игры": "game_development",
    "Медиа и развлечения": "media_entertainment",
    "Наука/образование": "higher_education",
    "Облачные сервисы": "cloud_services",
    "Потребительский интернет": "internet",
    "Промышленность": "manufacturing",
    "Рестораны / быстрое обслуживание": "restaurant",
    "Розничная торговля / потребительские товары в упаковке": "retail",
    "Сельское хозяйство": "agriculture",
    "Телекоммуникации": "telecommunications",
    "Умные города / пространства": "smart_spaces",
    "Финансовые услуги": "financial_services",
    "Энергетика": "energy",
    "Другое": "",
    "Akademi/Eğitim": "higher_education", // Translation tr-tr (turkish)
    "Akıllı Şehirler/Alanlar": "smart_spaces",
    "Bulut Hizmetleri": "cloud_services",
    "Donanım / Yarı İletken": "hardware",
    "Enerji": "energy",
    "Finans Hizmetleri": "financial_services",
    "Hava-Uzay": "aerospace",
    "HPC/Bilimsel Bilgi İşlem": "supercomputing",
    "Kamu Sektörü": "public_sector",
    "Medya ve Eğlence": "media_entertainment",
    "Mimarlık / Mühendislik / İnşaat": "architecture_engineering_construction",
    "Otomotiv / Ulaştırma": "automotive",
    "Oyun": "game_development",
    "Perakende/Paketlenmiş Tüketici Ürünleri": "retail",
    "Restoran/Hızlı Servis": "restaurant",
    "Sağlık ve Yaşam Bilimleri": "healthcare_lifesciences",
    "Tarım": "agriculture",
    "Telekomünikasyon": "telecommunications",
    "Tüketici İnterneti": "internet",
    "Üretim": "manufacturing",
    "Diğer": "",
    "Akademia/utdanning": "higher_education", // Translation  nb-no (norwegian)
    "Arkitektur/Ingeniørfag/Anleggsarbeid": "architecture_engineering_construction",
    "Bil/Transport": "automotive",
    "Detaljhandel / forbrukervarer": "retail",
    "Energi": "energy",
    "Finanstjenester": "financial_services",
    "Fly og romfart": "aerospace",
    "Helsefag og Biovitenskap": "healthcare_lifesciences",
    "HPC / Vitenskapelig databehandling": "supercomputing",
    "Internett for forbrukere": "internet",
    "Landbruk": "agriculture",
    "Maskinvare/Halvleder": "hardware",
    "Media og underholdning": "media_entertainment",
    "Offentlig sektor": "public_sector",
    "Produksjon": "manufacturing",
    "Restaurant / Rask service": "restaurant",
    "Skytjenester": "cloud_services",
    "Smarte byer / områder": "smart_spaces",
    "Spilling": "game_development",
    "Telekommunikasjon": "telecommunications",
    "Annet": "",
    "Akademi/utbildning": "higher_education",  // Translation sv-se (swedish)
    "Arkitektur/teknik/bygg": "architecture_engineering_construction",
    "Återförsäljare/förpackade konsumentvaror": "retail",
    "Energi": "energy",
    "Finansiella tjänster": "financial_services",
    "Fordon/transport": "automotive",
    "Hårdvara/halvledare": "hardware",
    "HPC/vetenskaplig databehandling": "supercomputing",
    "Internet för konsumenter": "internet",
    "Jordbruk": "agriculture",
    "Luft- och rymdfart": "aerospace",
    "Media och underhållning": "media_entertainment",
    "Molntjänster": "cloud_services",
    "Offentlig sektor": "public_sector",
    "Restaurang/snabbmat": "restaurant",
    "Sjukvård och biovetenskap": "healthcare_lifesciences",
    "Smarta städer/utrymmen": "smart_spaces",
    "Spel": "game_development",
    "Telekommunikation": "telecommunications",
    "Tillverkning": "manufacturing",
    "Annan": "",
    "Älykaupungit/-tilat": "smart_spaces", // Translation fi-fi (finnish)
    "Arkkitehtuuri / suunnittelu / rakennusala": "architecture_engineering_construction",
    "Autoteollisuus / liikenne": "automotive",
    "Energia-ala": "energy",
    "Ilmailu": "aerospace",
    "Julkinen sektori": "public_sector",
    "Korkeakoulu/opetus": "higher_education",
    "Kuluttaja-asiakkaiden internet": "internet",
    "Laitteistot / puolijohteet": "hardware",
    "Maatalous": "agriculture",
    "Media ja viihde": "media_entertainment",
    "Pelaaminen": "game_development",
    "Pilvipalvelut": "cloud_services",
    "Rahoituspalvelut": "financial_services",
    "Ravintola/pikaruokaravintola": "restaurant",
    "Suurteholaskenta / tieteellinen laskenta": "supercomputing",
    "Terveydenhoito ja biotieteet": "healthcare_lifesciences",
    "Tietoliikenne": "telecommunications",
    "Tuotanto": "manufacturing",
    "Vähittäismyynti/kuluttajatuotteet": "retail",
    "Muu": "",
    "Arkitektur/ingeniørarbejde/byggeri": "architecture_engineering_construction", // Translation da-dk (dannish)
    "Cloud-tjenester": "cloud_services",
    "Den akademiske verden/uddannelse": "higher_education",
    "Den offentlige sektor": "public_sector",
    "Detail-/forbrugervarer": "retail",
    "Energi": "energy",
    "Finansielle tjenesteydelser": "financial_services",
    "Forbrugerinternet": "internet",
    "Hardware/halvleder": "hardware",
    "HPC/videnskabelig databehandling": "supercomputing",
    "Intelligente byer/områder": "smart_spaces",
    "Landbrug": "agriculture",
    "Luftfartsindustrien": "aerospace",
    "Medier og underholdning": "media_entertainment",
    "Motorindustri/transport": "automotive",
    "Produktion": "manufacturing",
    "Restaurant/fastfood": "restaurant",
    "Spiludvikling": "game_development",
    "Sundheds- og biovidenskab": "healthcare_lifesciences",
    "Telekommunikation": "telecommunications",
    "Andet": "",
    "Akademická sféra / vzdělávání": "higher_education", // Transaltion cs-cz (czech)
    "Architektura/inženýrství/stavebnictví": "architecture_engineering_construction", 
    "Automobilový průmysl / doprava": "automotive",
    "Chytrá města / chytré prostory": "smart_spaces",
    "Cloudové služby": "cloud_services",
    "Energetika": "energy",
    "Finanční služby": "financial_services",
    "Hardware/polovodiče": "hardware",
    "HPC / vědecká výpočetní technika": "supercomputing",
    "Hraní": "game_development",
    "Letectví a kosmonautika": "aerospace",
    "Maloobchod / spotřební zboží": "retail",
    "Média a zábava": "media_entertainment",
    "Restaurace / rychlé občerstvení": "restaurant",
    "Spotřebitelský internet": "internet",
    "Telekomunikace": "telecommunications",
    "Veřejný sektor": "public_sector",
    "Výroba": "manufacturing",
    "Zdravotnictví a přírodní vědy": "healthcare_lifesciences", 
    "Zemědělství": "agriculture",
    "Jiné": "",
    "Architectuur/techniek/bouw": "architecture_engineering_construction", // Translation nl-nl (dutch)
    "Automotive/transport": "automotive",
    "Cloudservices": "cloud_services",
    "Consumenteninternet": "internet",
    "Detailhandel/verpakte consumentengoederen": "retail",
    "Energie": "energy",
    "Financiële dienstverlening": "financial_services",
    "Game-ontwikkeling": "game_development",
    "Gezondheidszorg en biowetenschappen": "healthcare_lifesciences",
    "Hardware/halfgeleider": "hardware",
    "Hoger onderwijs/academische wereld": "higher_education",
    "HPC/wetenschappelijke computing": "supercomputing",
    "Landbouw": "agriculture",
    "Lucht- en ruimtevaart": "aerospace",
    "Media en entertainment": "media_entertainment",
    "Productie": "manufacturing",
    "Publieke sector": "public_sector",
    "Restaurant/Snelle service": "restaurant",
    "Slimme steden/ruimtes": "smart_spaces",
    "Telecommunicatie": "telecommunications",
    "Anders": "",
    "Architektur/Maschinenbau/Baugewerbe": "architecture_engineering_construction", // Translation de-at (German)
    "Automobil-/Transportwesen": "automotive",
    "Cloud-Dienste": "cloud_services",
    "Consumer Internet": "internet",
    "Einzelhandel/Konsumgüter": "retail",
    "Energie": "energy",
    "Fertigung": "manufacturing",
    "Finanzdienstleistungen": "financial_services",
    "Gaming": "game_development",
    "Gesundheitswesen und Biowissenschaften": "healthcare_lifesciences",
    "Hardware/Halbleiter": "hardware",
    "HPC/Wissenschaftliches Rechnen": "supercomputing",
    "Landwirtschaft": "agriculture",
    "Luft‑ und Raumfahrt": "aerospace",
    "Medien und Unterhaltung": "media_entertainment",
    "Öffentlicher Sektor": "public_sector",
    "Restaurant / Quick-Service": "restaurant",
    "Smart Cities/Spaces": "smart_spaces",
    "Telekommunikation": "telecommunications",
    "Universität/Bildung": "higher_education",
    "Sonstige": "",
    "Aérospatiale": "aerospace",  //Translation fr-be (french)
    "Agriculture": "agriculture",
    "Architecture ingénierie et construction": "architecture_engineering_construction",
    "Automobile / Transport": "automotive",
    "Enseignement / Université": "higher_education",
    "Gaming": "game_development",
    "HPC / Calcul scientifique": "supercomputing",
    "Industrie énergétique": "energy",
    "Internet grand public": "internet",
    "Médias et divertissement": "media_entertainment",
    "Production": "manufacturing",
    "Produits matériels / Semi-conducteurs": "hardware",
    "Restauration rapide": "restaurant",
    "Santé et sciences de la vie": "healthcare_lifesciences",
    "Secteur public": "public_sector",
    "Services Cloud": "cloud_services",
    "Services financiers": "financial_services",
    "Télécommunications": "telecommunications",
    "Vente au détail / Biens de consommation courante": "retail",
    "Villes et espaces connectés": "smart_spaces",
    "Autre": "",
    "Aerospațial": "aerospace", // Translation ro-ro (romania)
    "Agricultură": "agriculture",
    "Arhitectură inginerie și construcții": "architecture_engineering_construction",
    "Energie": "energy",
    "Facultate/Învățământ": "higher_education",
    "Hardware/semiconductori": "hardware",
    "HPC/Calcul științific": "supercomputing",
    "Industria auto/Transport": "automotive",
    "Internet pentru consumatori": "internet",
    "Jocuri": "game_development",
    "Media și divertisment": "media_entertainment",
    "Medicină și sănătate": "healthcare_lifesciences",
    "Orașe/spații inteligente": "smart_spaces",
    "Producție": "manufacturing",
    "Restaurant/servire rapidă": "restaurant",
    "Retail/Bunuri de consum ambalate": "retail",
    "Sector public": "public_sector",
    "Servicii de cloud": "cloud_services",
    "Servicii financiare": "financial_services",
    "Telecomunicații": "telecommunications",
    "Alt motiv": "",
    "Aeroespacial": "aerospace", // Translation pt-br (portugese) 
    "Agricultura": "agriculture",
    "Área da Saúde e Ciências da Vida": "healthcare_lifesciences",
    "Arquitetura / Engenharia / Construção": "architecture_engineering_construction",
    "Automotivo / Transportes": "automotive",
    "Cidades Inteligentes / Espaços": "smart_spaces",
    "Energia": "energy",
    "Finanças": "financial_services",
    "Games": "game_development",
    "Hardware / Semicondutores": "hardware",
    "HPC/Computação Científica": "supercomputing",
    "Internet de Consumidor": "internet",
    "Manufatura": "manufacturing",
    "Meio Acadêmico/Educação": "higher_education",
    "Mídia e Entretenimento": "media_entertainment",
    "Restaurantes / Fast Food": "restaurant",
    "Serviços no Cloud": "cloud_services",
    "Setor Público": "public_sector",
    "Telecomunicações": "telecommunications",
    "Varejo/Produtos Empacotados para Consumidor": "retail",
    "Outros": ""
    

}

module.exports = industry_names;     