// allmachine names

var country_names = {  
	
    'AFGHANISTAN' : 'Afghanistan',
    'ALAND ISLANDS' : 'Aland Islands',
    'ALBANIA' : 'Albania',
    'ALGERIA' : 'Algeria',
    'AMERICAN SAMOA' : 'American Samoa',
    'ANDORRA' : 'Andorra',
    'ANGOLA' : 'Angola',
    'ANGUILLA' : 'Anguilla',
    'ANTARCTICA' : 'Antarctica',
    'ANTIGUA AND BARBUDA' : 'Antigua and Barbuda', 
    'ARGENTINA' : 'Argentina',
    'ARMENIA' : 'Armenia',
    'ARUBA' : 'Aruba',
    'AUSTRALIA' : 'Australia',
    'AUSTRIA' : 'Austria',
    'AZERBAIJAN' : 'Azerbaijan',
    'BAHAMAS' : 'Bahamas',
    'BAHRAIN' : 'Bahrain',
    'BANGLADESH' : 'Bangladesh',
    'BARBADOS' : 'Barbados',
    'BELARUS' : 'Belarus',
    'BELGIUM' : 'Belgium',
    'BELIZE' : 'Belize',
    'BENIN' : 'Benin',
    'BERMUDA' : 'Bermuda',
    'BHUTAN' : 'Bhutan',
    'BOLIVIA' : 'Bolivia',
    'BOSNIA AND HERZEGOVINA' : 'Bosnia and Herzegovina',
    'BOTSWANA' : 'Botswana',
    'BOUVET ISLAND' : 'Bouvet Island',
    'BRAZIL' : 'Brazil',
    'BRITISH INDIAN OCEAN TERRITORY' : 'British Indian Ocean Territory',
    'BRITISH VIRGIN ISLANDS' : 'British Virgin Islands',
    'BRUNEI DARUSSALAM' : 'Brunei Darussalam',
    'BULGARIA' : 'Bulgaria',
    'BURKINA FASO' : 'Burkina Faso',
    'BURUNDI' : 'Burundi',
    'CAMBODIA' : 'Cambodia',
    'CAMEROON' : 'Cameroon',
    'CANADA' : 'Canada',
    'CAPE VERDE' : 'Cape Verde',
    'CAYMAN ISLANDS' : 'Cayman Islands',
    'CENTRAL AFRICAN REPUBLIC' : 'Central African Republic',
    'CHAD' : 'Chad',
    'CHILE' : 'Chile',
    'CHINA' : 'china', 
    'CHRISTMAS ISLAND' : 'Christmas Island',
    'COCOS (KEELING) ISLANDS' : 'Cocos (Keeling) Islands',
    'COLOMBIA' : 'Colombia',
    'CONGO' : 'Congo',
    'COOK ISLANDS' : 'Cook Islands',
    'COSTA RICA' : 'Costa Rica',
    "COTE D'IVOIRE" : "Cote D'Ivoire",
    'CROATIA' : 'Croatia',
    'CUBA' : 'Cuba',
    'CURAÇAO' : 'Curaçao',
    'CYPRUS' : 'Cyprus',
    'CZECH REPUBLIC' : 'Czech Republic',
    'DENMARK' : 'Denmark',
    'DOMINICA' : 'Dominica',
    'DOMINICAN REPUBLIC' : 'Dominican Republic',
    'ECUADOR' : 'Ecuador',
    'EGYPT' : 'Egypt',
    'EL SALVADOR' : 'El Salvador',
    'EQUATORIAL GUINEA' : 'Equatorial Guinea',
    'ESTONIA' : 'Estonia',
    'ETHIOPIA' : 'Ethiopia',
    'FALKLAND ISLANDS (MALVINAS)' : 'Falkland Islands (Malvinas)',
    'FAROE ISLANDS' : 'Faroe Islands',
    'FIJI' : 'Fiji',
    'FINLAND' : 'Finland',
    'FRANCE' : 'France',
    'FRENCH GUIANA' : 'French Guiana',
    'FRENCH POLYNESIA' : 'French Polynesia',
    'FRENCH SOUTHERN TERRITORIES' : 'French Southern Territories',
    'GABON' : 'Gabon',
    'GEORGIA' : 'Georgia',
    'GERMANY' : 'Germany',
    'GHANA' : 'Ghana',
    'GIBRALTAR' : 'Gibraltar',
    'GREECE' : 'Greece',
    'GREENLAND' : 'Greenland',
    'GRENADA' : 'Grenada',
    'GUADELOUPE' : 'Guadeloupe',
    'GUATEMALA' : 'Guatemala',
    'GUERNSEY' : 'Guernsey',
    'GUINEA-BISSAU' : 'Guinea-Bissau',
    'GUYANA' : 'Guyana',
    'HAITI' : 'Haiti',
    'HEARD ISLAND AND MCDONALD ISLANDS' : 'Heard Island and Mcdonald Islands',
    'HONDURAS' : 'Honduras',
    'HONG KONG' : 'Hong Kong',
    'HUNGARY' : 'Hungary',
    'ICELAND' : 'Iceland',
    'INDIA' : 'India',
    'INDONESIA' : 'Indonesia',
    'IRAN' : 'Iran',
    'IRAQ' : 'Iraq',
    'IRELAND' : 'Ireland',
    'ISLE OF MAN' : 'Isle of Man', 
    'ISRAEL' : 'Israel',
    'ITALY' : 'Italy',
    'JAMAICA' : 'Jamaica',
    'JAPAN' : 'Japan',
    'JERSEY' : 'Jersey',
    'JORDAN' : 'Jordan',
    'KAZAKHSTAN' : 'Kazakhstan',
    'KENYA' : 'Kenya',
    'KIRIBATI' : 'Kiribati',
    "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF" : "Korea, Democratic People's Republic of",
    'KOREA, REPUBLIC OF' : 'Korea, Republic of',
    'KUWAIT' : 'Kuwait',
    'KYRGYZSTAN' : 'Kyrgyzstan',
    "LAO PEOPLE'S DEMOCRATIC REPUBLIC" : "Lao People's Democratic Republic",
    'LATVIA' : 'Latvia',
    'LEBANON' : 'Lebanon',
    'LESOTHO' : 'Lesotho',
    'LIBERIA' : 'Liberia',
    'LIBYA' : 'Libya',
    'LIECHTENSTEIN' : 'Liechtenstein',
    'LITHUANIA' : 'Lithuania',
    'LUXEMBOURG' : 'Luxembourg',
    'MACAO' : 'Macao',
    'MACEDONIA' : 'Macedonia',
    'MADAGASCAR' : 'Madagascar',
    'MALAWI' : 'Malawi',
    'MALAYSIA' : 'Malaysia',
    'MALDIVES' : 'Maldives',
    'MALI' : 'Mali',
    'MALTA' : 'Malta',
    'MARTINIQUE' : 'Martinique',
    'MAURITANIA' : 'Mauritania',
    'MAURITIUS' : 'Mauritius',
    'MAYOTTE' : 'Mayotte',
    'MEXICO' : 'Mexico',
    'MICRONESIA, FEDERATED STATES OF' : 'Micronesia, Federated States of',
    'MOLDOVA, REPUBLIC OF' : 'Moldova, Republic of',
    'MONACO' : 'Monaco',
    'MONGOLIA' : 'Mongolia',
    'MONTENEGRO' : 'Montenegro',
    'MONTSERRAT' : 'Montserrat',
    'MOROCCO' : 'Morocco',
    'MOZAMBIQUE' : 'Mozambique',
    'MYANMAR' : 'Myanmar',
    'NAMIBIA' : 'Namibia',
    'NAURU' : 'Nauru',
    'NEPAL' : 'Nepal',
    'NETHERLANDS ANTILLES' : 'Netherlands Antilles',
    'NEW CALEDONIA' : 'New Caledonia',
    'NEW ZEALAND' : 'New Zealand',
    'NICARAGUA' : 'Nicaragua',
    'NIGER' : 'Niger',
    'NIGERIA' : 'Nigeria',
    'NIUE' : 'Niue',
    'NORFOLK ISLAND' : 'Norfolk Island',
    'NORWAY' : 'Norway',
    'OMAN' : 'Oman',
    'PAKISTAN' : 'Pakistan',
    'PALAU' : 'Palau',
    'PALESTINIAN TERRITORY, OCCUPIED' : 'Palestinian Territory, Occupied',
    'PANAMA' : 'Panama',
    'PAPUA NEW GUINEA' : 'Papua New Guinea',
    'PARAGUAY' : 'Paraguay',
    'PERU' : 'Peru',
    'PHILIPPINES' : 'Philippines',
    'PITCAIRN' : 'Pitcairn',
    'POLAND' : 'Poland',
    'PORTUGAL' : 'Portugal',
    'PUERTO RICO' : 'Puerto Rico',
    'QATAR' : 'Qatar',
    'ROMANIA' : 'Romania',
    'RUSSIAN FEDERATION' : 'Russian Federation',
    'RWANDA' : 'Rwanda',
    'SAINT HELENA' : 'Saint Helena',
    'SAINT LUCIA' : 'Saint Lucia',
    'SAINT-BARTHÉLEMY' : 'Saint-Barthélemy',
    'SAINT-MARTIN (FRENCH PART)' : 'Saint-Martin (French part)',
    'SAN MARINO' : 'San Marino',
    'SAO TOME AND PRINCIPE' : 'Sao Tome and Principe',
    'SAUDI ARABIA' : 'Saudi Arabia',
    'SENEGAL' : 'Senegal',
    'SERBIA' : 'Serbia',
    'SEYCHELLES' : 'Seychelles',
    'SIERRA LEONE' : 'Sierra Leone',
    'SINGAPORE' : 'Singapore',
    'SLOVAKIA' : 'Slovakia',
    'SLOVENIA' : 'Slovenia',
    'SOLOMON ISLANDS' : 'Solomon Islands',
    'SOMALIA' : 'Somalia',
    'SOUTH AFRICA' : 'South Africa',
    'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS' : 'South Georgia and the South Sandwich Islands',
    'SOUTH SUDAN' : 'South Sudan',
    'SPAIN' : 'Spain',
    'SRI LANKA' : 'Sri Lanka',
    'SUDAN' : 'Sudan',
    'SURINAME' : 'Suriname',
    'SWAZILAND' : 'Swaziland',
    'SWEDEN' : 'Sweden',
    'SWITZERLAND' : 'Switzerland',
    'SYRIA' : 'Syria',
    'TAIWAN' : 'Taiwan',
    'TAJIKISTAN' : 'Tajikistan',
    'TANZANIA' : 'Tanzania',
    'THAILAND' : 'Thailand',
    'THE NETHERLANDS' : 'The Netherlands',
    'TIMOR-LESTE' : 'Timor-Leste',
    'TOGO' : 'Togo',
    'TOKELAU' : 'Tokelau',
    'TONGA' : 'Tonga',
    'TRINIDAD AND TOBAGO' : 'Trinidad and Tobago',
    'TUNISIA' : 'Tunisia',
    'TURKEY' : 'Turkey',
    'TURKMENISTAN' : 'Turkmenistan',
    'TURKS AND CAICOS ISLANDS' : 'Turks and Caicos Islands',
    'TUVALU' : 'Tuvalu',
    'UGANDA' : 'Uganda',
    'UKRAINE' : 'Ukraine',
    'UNITED ARAB EMIRATES' : 'United Arab Emirates',
    'UNITED KINGDOM' : 'United Kingdom',
    'United States' : 'United States',
    'UNITED STATES MINOR OUTLYING ISLANDS' : 'United States Minor Outlying Islands',
    'URUGUAY' : 'Uruguay',
    'UZBEKISTAN' : 'Uzbekistan',
    'VANUATU' : 'Vanuatu',
    'VATICAN CITY STATE' : 'Vatican City State',
    'VENEZUELA' : 'Venezuela',
    'VIET NAM' : 'Viet Nam',
    'VIRGIN ISLANDS, U.S.' : 'Virgin Islands, U.S.',
    'WESTERN SAHARA' : 'Western Sahara',
    'YEMEN' : 'Yemen',
    'ZAMBIA' : 'Zambia',
    'ZIMBABWE' : 'Zimbabwe'
        
        }
    
    
   module.exports  = country_names;   
    